# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8a2171e40b8260d8f1788b9e428e6cee74921c82f0b34c5c0fbf4076fd615cbfe2f695e4dfcdbb914c3cfa84a54eb7a6066be41a71aa551055ae846bd669f7f

test:
  secret_key_base: 8bc97ae36ae258f675538f9c5788966b144f95e630482d073db01d2ef22d3a47cb02d9457cc31e7ce872fc0df3a2ddd0f44ad4e07a9b0b3d6180781bbde0d2ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
